from __future__ import annotations

import argparse
import html
import json
import subprocess
from pathlib import Path
from typing import Any


DOCS_ROOT = Path(__file__).resolve().parents[1]
GENERATED_REFERENCE = DOCS_ROOT / "docs/reference/cli/mask-op-intersect.md"
REFERENCE_FIELDS = (
    "Purpose",
    "Availability",
    "Inputs",
    "Types",
    "Shapes",
    "Dtypes",
    "Defaults",
    "Choices",
    "Constraints",
    "Outputs",
    "Ordering",
    "Side effects",
    "Failures",
)


def _run(command: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        command,
        cwd=DOCS_ROOT,
        check=True,
        capture_output=True,
        text=True,
    )


def _extract_parser_reference(code_root: Path) -> dict[str, Any]:
    code_python = code_root / ".venv/bin/python"
    if not code_python.is_file():
        raise RuntimeError(
            f"Missing {code_python}; create code/.venv and install code/pyproject.toml"
        )
    completed = _run(
        [
            str(code_python),
            "scripts/extract_mask_op_reference.py",
            "--code-root",
            str(code_root),
        ]
    )
    return json.loads(completed.stdout)


def _render_cli_reference(reference: dict[str, Any]) -> str:
    rows = []
    for argument in reference["arguments"]:
        choices = ", ".join(f"`{choice}`" for choice in argument["choices"])
        rows.append(
            "| {flags} | {required} | {value_type} | {choices} | {default} | {repeatable} | {help_text} |".format(
                flags=f"`{argument['flags']}`",
                required="yes" if argument["required"] else "no",
                value_type=f"`{argument['type']}`",
                choices=choices or "inapplicable",
                default=f"`{argument['default']}`",
                repeatable="yes" if argument["repeatable"] else "no",
                help_text=argument["help"],
            )
        )
    table = "\n".join(rows)
    return f"""<!-- Generated by scripts/build_release_docs.py; do not edit directly. -->

# `GenomicElementTools mask_op intersect`

## Purpose

Compute the element-wise logical AND across aligned boolean mask annotations.
This is boolean array algebra, not genomic interval intersection.

## Availability

Supported in `GenomicElementTools` for release `0.1.0a2`. Invoke it through the
installed `GenomicElementTools` console script.

## Syntax

This syntax and argument inventory are generated from the released argparse
parser during the documentation acceptance build.

```text
{reference['usage']}
```

| Flags | Required | Type | Choices | Default | Repeatable | Parser help |
| --- | --- | --- | --- | --- | --- | --- |
{table}

Although argparse exposes `bed3` as the `--region_file_type` default, the flag
is required, so omission is an argparse error rather than use of that default.

## Inputs

- `--region_file_path`: a headerless supported BED-like region table. Its row
  count establishes mask length and alignment.
- `--region_file_type`: the region schema key shown in the generated choices.
- `--mask_npy`: a `.npy` array or `.npz` containing exactly one array. Supply
  the flag at least twice.

## Types

Paths and the region type key are strings. Each loaded mask is a NumPy array.

## Shapes

Each mask must have shape `(N,)` or `(N, 1)`, where `N` is the number of region
rows. The saved result has shape `(N, 1)`.

## Dtypes

Every input mask and the output use NumPy boolean dtype. See the
[boolean-mask format](../formats/boolean-mask.md#dtype).

## Defaults

No semantic input or output default applies: all four non-help flags are
required. The parser metadata default for `--region_file_type` is described
under Syntax because the required flag prevents that default from taking effect.

## Choices

`--region_file_type` accepts exactly the parser-derived choices in the table.
The remaining flags have no enumerated choices.

## Constraints

Provide at least two masks. All masks must have boolean dtype, an accepted
shape, and first-dimension alignment with the region table. A single-array NPZ
is accepted; a multi-array NPZ is rejected.

## Outputs

`--opath` receives a NumPy `.npy` boolean mask containing the logical AND of all
inputs. Use a `.npy` suffix; if the supplied path has no suffix, NumPy appends
`.npy`. The filename is not used to select another output format.

## Ordering

Output row `i` corresponds to region row `i`. Input mask order does not change
the result because logical AND is commutative.

## Side effects

Reads the region and mask files and writes or replaces the file at `--opath`
(or `--opath.npy` when NumPy appends the missing suffix). No region table is
modified.

## Failures

Argparse exits for missing required flags or invalid region-type choices. The
command raises `ValueError` for fewer than two masks, non-boolean masks, shape
or region-count mismatches, multi-array NPZ input, or an unsupported region
schema encountered while loading.
"""


def _validate_built_artifact(site_dir: Path) -> None:
    pages = {
        "python": site_dir / "reference/python/general-elements/load-mask-from-arr/index.html",
        "format": site_dir / "reference/formats/boolean-mask/index.html",
        "cli": site_dir / "reference/cli/mask-op-intersect/index.html",
    }
    for name, path in pages.items():
        if not path.is_file():
            raise RuntimeError(f"Missing built {name} reference: {path}")

    for name in ("python", "cli"):
        rendered = html.unescape(pages[name].read_text())
        missing = [field for field in REFERENCE_FIELDS if f">{field}<" not in rendered]
        if missing:
            raise RuntimeError(f"Built {name} reference lacks fields: {missing}")

    format_html = " ".join(html.unescape(pages["format"].read_text()).split())
    for required in ("numpy.bool_", "Integer masks", "(N, 1)"):
        if required not in format_html:
            raise RuntimeError(f"Boolean-mask artifact lacks {required!r}")

    llms_path = site_dir / "llms.txt"
    if not llms_path.is_file():
        raise RuntimeError("Built artifact lacks llms.txt")
    dtype_url = (
        "https://dignomor.github.io/xp-genomic-tools-docs/"
        "reference/formats/boolean-mask/#dtype"
    )
    if dtype_url not in llms_path.read_text():
        raise RuntimeError("llms.txt does not link directly to the mask dtype rule")

    for path in (*pages.values(), llms_path):
        content = path.read_text().lower()
        if any(marker in content for marker in ("/specs/", "delivery-spec", "spec002")):
            raise RuntimeError(f"Private specification material leaked into {path}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate parser-derived reference, build strictly, and verify it."
    )
    parser.add_argument("--code-root", type=Path, required=True)
    parser.add_argument("--site-dir", type=Path, required=True)
    args = parser.parse_args()

    reference = _extract_parser_reference(args.code_root.resolve())
    GENERATED_REFERENCE.parent.mkdir(parents=True, exist_ok=True)
    GENERATED_REFERENCE.write_text(_render_cli_reference(reference))

    _run(
        [
            str(DOCS_ROOT / ".venv/bin/mkdocs"),
            "build",
            "--strict",
            "--clean",
            "--site-dir",
            str(args.site_dir.resolve()),
        ]
    )
    _validate_built_artifact(args.site_dir.resolve())
    print(f"Verified release documentation artifact at {args.site_dir.resolve()}")


if __name__ == "__main__":
    main()
